[codegen/python] Update Python codegen to use a non-conflicting property name
Fixes: https://github.com/pulumi/pulumi-aws/issues/1519

There is a realistic change that a mapped property is called `resource_name` and
this would conflict with the internal property `resource_name`.

Mypy reports an sdk error here:

```
dk/python/pulumi_aws/servicecatalog/tag_option_resource_association.py:277: error: Duplicate argument 'resource_name' in function definition
Found 1 error in 1 file (errors prevented further checking)
```

It's better to move the python internal property to something that
won't conflict, `resource_name_` in this case